# Generated by Django 6.0.1 on 2026-01-11 12:11

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_provider', models.CharField(blank=True, default='', max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, default='', max_length=64)),
                ('length_in', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('width_in', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('height_in', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('weight_lbs', models.PositiveIntegerField(default=0)),
                ('weight_oz', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('reviewed', 'Reviewed'), ('shipping_selected', 'Shipping Selected'), ('purchased', 'Purchased')], default='uploaded', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'upload session',
                'verbose_name_plural': 'upload sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_service', models.CharField(blank=True, default='', max_length=128)),
                ('price_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('order_number', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('created', 'Created'), ('validated', 'Validated'), ('shipping_selected', 'Shipping Selected'), ('purchased', 'Purchased'), ('cancelled', 'Cancelled')], default='created', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipments.package')),
                ('ship_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_from', to='shipments.address')),
                ('ship_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_to', to='shipments.address')),
                ('upload_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='shipments.uploadsession')),
            ],
            options={
                'verbose_name': 'shipment',
                'verbose_name_plural': 'shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_addresses', to='shipments.address')),
            ],
            options={
                'verbose_name': 'saved address',
                'verbose_name_plural': 'saved addresses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['label'], name='shipments_s_label_fb3200_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_packages', to='shipments.package')),
            ],
            options={
                'verbose_name': 'saved package',
                'verbose_name_plural': 'saved packages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['label'], name='shipments_s_label_f704ab_idx')],
            },
        ),
    ]
