# Generated by Django 6.0.1 on 2026-01-14 10:43

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_provider', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('length_in', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('width_in', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('height_in', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('weight_lbs', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('weight_oz', models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(15)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validating', 'Validating'), ('validated', 'Validated'), ('partial_valid', 'Partial Valid'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('failed', 'Failed'), ('ready_for_purchase', 'Ready for Purchase'), ('purchased', 'Purchased')], default='uploaded', max_length=32)),
                ('rows_total', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('rows_valid', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('rows_invalid', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'upload session',
                'verbose_name_plural': 'upload sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(blank=True, help_text='CSV row number for upload tracking', null=True)),
                ('shipping_service', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('shipping_option', models.CharField(blank=True, default=None, help_text="Shipping option: 'ground' or 'priority'", max_length=32, null=True)),
                ('price_cents', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('order_number', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('validated', 'Validated'), ('partial_valid', 'Partial Valid'), ('invalid', 'Invalid'), ('ready_for_purchase', 'Ready for Purchase'), ('purchased', 'Purchased'), ('cancelled', 'Cancelled')], default='created', max_length=32)),
                ('validation_status', models.CharField(choices=[('valid', 'Valid'), ('partial', 'Partial'), ('invalid', 'Invalid'), ('blank', 'Blank')], default='invalid', max_length=16)),
                ('validation_errors', models.JSONField(blank=True, default=dict, null=True)),
                ('pricing_status', models.CharField(choices=[('priced', 'Priced'), ('unpriced', 'Unpriced'), ('error', 'Error')], default='unpriced', max_length=16)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipments.package')),
                ('ship_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_from', to='shipments.address')),
                ('ship_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_to', to='shipments.address')),
                ('upload_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='shipments.uploadsession')),
            ],
            options={
                'verbose_name': 'shipment',
                'verbose_name_plural': 'shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_addresses', to='shipments.address')),
            ],
            options={
                'verbose_name': 'saved address',
                'verbose_name_plural': 'saved addresses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['label'], name='shipments_s_label_fb3200_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_packages', to='shipments.package')),
            ],
            options={
                'verbose_name': 'saved package',
                'verbose_name_plural': 'saved packages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['label'], name='shipments_s_label_f704ab_idx')],
            },
        ),
    ]
