# Generated by Django 6.0.1 on 2026-01-12 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pricing_status',
            field=models.CharField(choices=[('priced', 'Priced'), ('unpriced', 'Unpriced'), ('error', 'Error')], default='unpriced', max_length=16),
        ),
        migrations.AddField(
            model_name='shipment',
            name='validation_errors',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='validation_status',
            field=models.CharField(choices=[('valid', 'Valid'), ('partial', 'Partial'), ('invalid', 'Invalid'), ('blank', 'Blank')], default='invalid', max_length=16),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='filename',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='rows_invalid',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='rows_total',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='rows_valid',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line2',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='verification_provider',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='sku',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='weight_lbs',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='weight_oz',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='order_number',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='price_cents',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipping_service',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('validated', 'Validated'), ('partial_valid', 'Partial Valid'), ('invalid', 'Invalid'), ('ready_for_purchase', 'Ready for Purchase'), ('purchased', 'Purchased'), ('cancelled', 'Cancelled')], default='created', max_length=32),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('validating', 'Validating'), ('validated', 'Validated'), ('partial_valid', 'Partial Valid'), ('failed', 'Failed'), ('ready_for_purchase', 'Ready for Purchase'), ('purchased', 'Purchased')], default='uploaded', max_length=32),
        ),
    ]
