# Generated by Django 6.0.1 on 2026-01-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipment_locked_shipment_pricing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='row_number',
            field=models.PositiveIntegerField(blank=True, help_text='CSV row number for upload tracking', null=True),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('validating', 'Validating'), ('validated', 'Validated'), ('partial_valid', 'Partial Valid'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('failed', 'Failed'), ('ready_for_purchase', 'Ready for Purchase'), ('purchased', 'Purchased')], default='uploaded', max_length=32),
        ),
    ]
