# Generated by Django 6.0.1 on 2026-01-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_shipment_row_number_alter_uploadsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipping_option',
            field=models.CharField(blank=True, default=None, help_text="Shipping option: 'ground' or 'priority'", max_length=32, null=True),
        ),
    ]
