"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Security settings
SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # Django REST Framework
    'corsheaders',     # CORS headers
    'shipments',       # Your shipments app
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Security settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True


ADDRESS_VERIFICATION_CHAIN = [
    {
        'name': 'usps',
        'enabled': True,
        'countries': ['US'],
        'daily_limit': None,  # No hard limit
    },
    {
        'name': 'geoapify',
        'enabled': True,
        'countries': ['*'],  # Global
        'daily_limit': 3000,
    },
    {
        'name': 'here',
        'enabled': True,
        'countries': ['*'],
        'daily_limit': 1000,
    },
    {
        'name': 'mapbox',
        'enabled': True,
        'countries': ['*'],
        'monthly_limit': 100000,
    },
    {
        'name': 'google',
        'enabled': False,  # Enable when ready to pay
        'countries': ['*'],
        'cost_per_1000': 5.00,
    },
]

# Address Verification configuration (API keys, cache TTL, circuit breakers)
from decouple import config
ADDRESS_VERIFICATION = {
    'USPS_USER_ID': config('USPS_USER_ID', default=''),
    'GEOAPIFY_API_KEY': config('GEOAPIFY_API_KEY', default=''),
    'HERE_API_KEY': config('HERE_API_KEY', default=''),
    'MAPBOX_ACCESS_TOKEN': config('MAPBOX_ACCESS_TOKEN', default=''),
    'GOOGLE_API_KEY': config('GOOGLE_API_KEY', default=''),
    'CACHE_TTL': int(config('ADDRESS_VERIFICATION_CACHE_TTL', default=30 * 24 * 60 * 60)),  # 30 days
    'CIRCUIT_BREAKER_THRESHOLD': int(config('ADDRESS_VERIFICATION_CIRCUIT_BREAKER_THRESHOLD', default=5)),
    'CIRCUIT_BREAKER_TIMEOUT': int(config('ADDRESS_VERIFICATION_CIRCUIT_BREAKER_TIMEOUT', default=300)),
}
