# Column mapping (indices 0–22)
CSV_COLUMN_MAP = {
    0: 'ship_from_first_name',
    1: 'ship_from_last_name',
    2: 'ship_from_address_line1',
    3: 'ship_from_address_line2',
    4: 'ship_from_city',
    5: 'ship_from_postal_code',
    6: 'ship_from_state',
    7: 'ship_to_first_name',
    8: 'ship_to_last_name',
    9: 'ship_to_address_line1',
    10: 'ship_to_address_line2',
    11: 'ship_to_city',
    12: 'ship_to_postal_code',
    13: 'ship_to_state',
    14: 'weight_lbs',
    15: 'weight_oz',
    16: 'length_in',
    17: 'width_in',
    18: 'height_in',
    19: 'ship_to_phone1',
    20: 'ship_to_phone2',
    21: 'order_number',
    22: 'sku',
}